server:
  port: 8090 #端口
spring:
  application:
    name: express-pickup #应用名称
  datasource:
    #    数据源
    url: jdbc:mysql://119.3.104.52:3306/expressPickup?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MySQL8.0
  devtools:
    restart:
      # 热部署生效
      enabled: true
      # 设置需要重启的目录
      additional-paths: src/main/java
      # 设置不需要重启的目录
      exclude: static/**,public/**,WEB-INF/**
  redis:
    database: 0
    host: 119.3.104.52
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 300000
    lettuce:
      shutdown-timeout: 30000
mybatis-plus:
  #  xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath*:mapper/**/*.xml
  # 别名包路径
  type-aliases-package: com.xiaofei.expresspickup.entity
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: assign_uuid
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      # field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
      # 表名不使用下划线
      table-underline: true
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: false
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
swagger:
  enabled: true
# 设置 jwt, 涉及时间单位均为秒
jwt:
  # 设置 Token 过期时间
  expiration: 10
  # 设置 JWT 的密钥
  secret: xiaofei00152
  # 设置记住密码的时间
  remember-time: 1296000
  # 设置小于某个时间, 自动更新 Token
  validate-time: 300
  pagehelper:
    auto-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    page-size-zero: true
    params: count=countSql